version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      time: '09:00'
      timezone: 'Europe/Madrid'
    open-pull-requests-limit: 10
    groups:
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      types:
        patterns:
          - '@types/*'
      swagger:
        patterns:
          - 'swagger-ui'
          - 'swagger-ui-react'
      vite:
        patterns:
          - 'vite'
          - '@vitejs/*'
      eslint:
        patterns:
          - '@shlinkio/eslint-config-js-coding-standard'
          - 'typescript-eslint'
          - '*eslint-plugin*'
          - eslint
      tailwindcss:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      time: '09:00'
      timezone: 'Europe/Madrid'
