language: node_js

node_js:
  - "12.9.1"

cache:
  directories:
    - node_modules

services:
  - docker

install:
  - npm ci

script:
  - npm run lint
  - if [[ -z $TRAVIS_TAG ]]; then docker build -t shlink-website:test . ; fi
