language: node_js

node_js:
  - "14.15.1"

cache:
  directories:
    - node_modules

services:
  - docker

install:
  - npm ci

script:
  - npm run lint
  - if [[ $TRAVIS_PULL_REQUEST != 'false' ]]; then docker build -t shlink-website:test . ; fi

deploy:
  - provider: script
    script: bash ./scripts/docker/build
    on:
      all_branches: true
      condition: $TRAVIS_PULL_REQUEST == 'false'
