services:
  shlink_api_spec_ui:
    container_name: shlink_api_spec_ui
    user: 1000:1000
    image: node:22.10-alpine
    working_dir: '/shlink-api-spec'
    command: /bin/sh -c "npm install && npm run start"
    volumes:
      - ./:/shlink-api-spec
    ports:
      - "3000:3000"
