name: Build docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    uses: shlinkio/github-actions/.github/workflows/docker-build-and-publish.yml@main
    secrets: inherit
    with:
      image-name: shlinkio/shlink-api-spec-ui
      platforms: linux/amd64
